# Generated by Django 3.2.5 on 2021-07-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadstate',
            name='name',
            field=models.CharField(choices=[(1, 'Новый'), (2, 'В работе'), (3, 'Приостановлен'), (4, 'Завершен')], max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
