# Generated by Django 3.2.5 on 2021-07-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_2', '0002_alter_leadstate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_2.leadstate', verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='leadstate',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
