# Generated by Django 3.2.5 on 2021-07-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_2', '0003_auto_20210703_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstate',
            name='state',
            field=models.CharField(choices=[(1, 'Новый'), (2, 'В работе'), (3, 'Приостановлен'), (4, 'Завершен')], default=1, max_length=100, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
