# Generated by Django 3.2.5 on 2021-07-03 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_2', '0004_leadstate_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadstate',
            name='state',
        ),
        migrations.AlterField(
            model_name='lead',
            name='state',
            field=models.ForeignKey(choices=[(1, 'Новый'), (2, 'В работе'), (3, 'Приостановлен'), (4, 'Завершен')], on_delete=django.db.models.deletion.PROTECT, to='task_2.leadstate', verbose_name='Состояние'),
        ),
    ]
